package require ::quartus::project

set_location_assignment PIN_131 -to CLK
set_location_assignment PIN_12 -to BUTTON[7]
set_location_assignment PIN_11 -to BUTTON[6]
set_location_assignment PIN_10 -to BUTTON[5]
set_location_assignment PIN_8 -to BUTTON[4]
set_location_assignment PIN_6 -to BUTTON[3]
set_location_assignment PIN_5 -to BUTTON[2]
set_location_assignment PIN_4 -to BUTTON[1]
set_location_assignment PIN_3 -to BUTTON[0]
set_location_assignment PIN_44 -to BIT_A
set_location_assignment PIN_40 -to BIT_B
set_location_assignment PIN_45 -to BIT_C
set_location_assignment PIN_47 -to BIT_D
set_location_assignment PIN_46 -to BIT_DP
set_location_assignment PIN_48 -to BIT_E
set_location_assignment PIN_41 -to BIT_F
set_location_assignment PIN_43 -to BIT_G
set_location_assignment PIN_39 -to DIG[3]
set_location_assignment PIN_37 -to DIG[2]
set_location_assignment PIN_36 -to DIG[1]
set_location_assignment PIN_35 -to DIG[0]
set_location_assignment PIN_56 -to LED[7]
set_location_assignment PIN_57 -to LED[6]
set_location_assignment PIN_58 -to LED[5]
set_location_assignment PIN_59 -to LED[4]
set_location_assignment PIN_60 -to LED[3]
set_location_assignment PIN_61 -to LED[2]
set_location_assignment PIN_63 -to LED[1]
set_location_assignment PIN_64 -to LED[0]
set_location_assignment PIN_13 -to C[3]
set_location_assignment PIN_14 -to C[2]
set_location_assignment PIN_15 -to C[1]
set_location_assignment PIN_30 -to C[0]
set_location_assignment PIN_31 -to R[3]
set_location_assignment PIN_32 -to R[2]
set_location_assignment PIN_33 -to R[1]
set_location_assignment PIN_34 -to R[0]
set_location_assignment PIN_152 -to SYNTH
set_location_assignment PIN_116 -to IDKEY[3]
set_location_assignment PIN_115 -to IDKEY[2]
set_location_assignment PIN_114 -to IDKEY[1]
set_location_assignment PIN_113 -to IDKEY[0]
